export const CREATE_COMMENT = 'COMMENTS/CREATE_COMMENT'
export const REMOVE_COMMENT = 'COMMENTS/REMOVE_COMMENT'
export const FETCH_COMMENTS = 'STORAGE/FETCH_COMMENTS'
export const UPDATE_STORAGE = 'STORAGE/UPDATE_COMMENTS'